### ISSUE TITLE
Enable VIP posting button

### ISSUE THREAD

**Issue by ciakval** [ciakval/phpbb-vipposts#1]
The 'mark post as VIP' posting button is currently present, but checking it does not result in proper database field update.

Make sure the field _post_vip_ in the _<prefix>_posts_ table is set to TRUE when a post with 'Mark post as VIP' button checked is submitted.

**Comment by bruninoit** [comment]
I don't see the field code here

**Comment by ciakval** [comment]
Solved - the data can be obtained through request_var() and saved through your code
