### ISSUE TITLE
Add VIP posts highlighting to search results and MCP view

### ISSUE THREAD

**Issue by ciakval** [ciakval/phpbb-vipposts#10]
The VIP posts are highlighted only in the topic view page (viewtopic.php). They should also be highlighted in the search results (search_results.html) and MCP topic view (posting_topic_review.html).

**Comment by ciakval** [comment]
I have added highlighting to the search page.

@R3gi, could you please make me a screenshot of the MCP page where the post highlighting should be?

**Comment by R3gi** [comment]
@ciakval Sure. It would be good to highlight the post in the top and also all posts in the list under it.

![vip post in mcp](https://cloud.githubusercontent.com/assets/2983869/12464897/c06a5fbc-bfcb-11e5-8911-2e2c8312e020.png)

**Comment by ciakval** [comment]
The corresponding style files for MCP review page have no  inside the looping part. That makes it (to my knowledge) impossible to introduce any HTML (except by means of JavaScript) and hence impossible to highlight.

Won't fix until better solution is available.
