### ISSUE TITLE
Add "Submit as VIP" button to the post editing page

### ISSUE THREAD

**Issue by ciakval** [ciakval/phpbb-vipposts#11]
Add "Submit as VIP" button to the "Submit" and "Preview" buttons in the post editing page. The button should submit the post as VIP, regardless of the "Mark as VIP" button state.

**Comment by bruninoit** [comment]
There is just the option... Not?

**Comment by ciakval** [comment]
Yes. Currently there is just the option.

The button would, however, be better for forum users, who don't read through the options (rumour goes they have trouble uploading an attachment).

So this is a "nice-to-have" feature.

**Comment by bruninoit** [comment]
Ok, I'll see.

**Comment by ciakval** [comment]
Button with desired functionality added.
