### ISSUE TITLE
Set permissions for proper groups and roles

### ISSUE THREAD

**Issue by ciakval** [ciakval/phpbb-vipposts#5]
Set extension permissions for VIP users (view, post), moderators and admins (view, post, set).

**Comment by bruninoit** [comment]
Now I insert the code that was on dev... So let's update.

**Comment by ciakval** [comment]
There should be a user group called "VIP" which will have Standard User permissions + VIP post and VIP view permissions.

**Comment by bruninoit** [comment]
Bhe but it's set by Admin not by us... Also because we cannot know well which is the group called VIP... It's more simple that Admin set it.
