### ISSUE TITLE
Create configuration page

### ISSUE THREAD

**Issue by ciakval** [ciakval/phpbb-vipposts#7]
Several features of the extension should be available for the site admin to enable or disable.

Prepare configuration values for those and create a configuration page where they can be changed.

**Comment by bruninoit** [comment]
OK... An ACP Page will arrive

**Comment by ciakval** [comment]
I have assigned myself to this, meaning that I am going to do it :-) I create these issues for everyone to know what is going on and to phrase intentions with the extension, not as tasks for you.

If you want to work on some issue, please, assign it to yourself.

**Comment by ciakval** [comment]
My existing work is in the issue-7-conf-page branch, will merge it to master as soon as it works completely.

**Comment by bruninoit** [comment]
Okok...

**Comment by ciakval** [comment]
Page created and merged to main. So far with highlight config support.
