### ISSUE TITLE
Configurable: Substitute VIP posts with custom text

### ISSUE THREAD

**Issue by ciakval** [ciakval/phpbb-vipposts#9]
Instead of hiding VIP posts for non-VIP users, show them a post with customizable text, something like "This post is for VIP members only".
- The feature is configurable (by default, VIP posts are hidden)
- The contents of the replacement post are configurable

**Comment by bruninoit** [comment]
Ok, I'll add...Are you sure is better to insert it in a configuration and not in language file?

**Comment by R3gi** [comment]
Maybe loading from language files by default and overwrite it with the content from ACP when changed?

**Comment by ciakval** [comment]
It should be manually configurable. Therefore, it must be stored in the DB (there is the config_text table) rather than in a file, which is not supposed to be modified by forum admin.

**Comment by bruninoit** [comment]
Ok.

**Comment by bruninoit** [comment]
I think it's competed.

**Comment by bruninoit** [comment]
*completed

**Comment by ciakval** [comment]
The functionality was supposed to be a little different. The feature works now (since the **Bold Bear** release)
